name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    name: unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: action/checkout@v2
      - name: Run test
        run: make && ./test
